### ISSUE TITLE
Page 152, the ORDER BY in window function does not make sense

### ISSUE THREAD

**Issue by shepard8** [PacktPublishing/Learn-PostgreSQL#6]
Hello dear authors,

This is not an error stricto sensu, but on page 152, in the following query:

```sql
select category, row_number() over w, title, last_value(title) over w
from posts WINDOW w as (partition by category order by category) order by category;
```

The first `order by category` does not make sense. I believe putting it in the erratum or updating the query in the code of chapter 5 would mislead the reader, but maybe you want to note this somewhere for a future second edition?

I guess your initial intent was to put `order by title` there.

**Comment by sscotty71** [comment]
Hello sheparrd8,
Thanks for reporting, it was a transcription error, originally it was

select category, row_number () over w, title, last_value (title) over w
from posts WINDOW w as (partition by category order by title) order by category;

so that the row_number () was tied to the title.

Thanks again for your help
Enrico
